fix_rocketchat
MagalixTechnologies/templates pull request #27
Opened 2018-06-21 14:58 UTC by Zahaby-magalix

fix rocket chat , as mongodb docker version is not working after adding validation to the UI

2018-06-22 09:44 UTC, gagliardetto commented on stable/rocketchat/template.json
> +		"size": 10
The max volume size allowed is 8 (GB)

2018-06-22 09:44 UTC, gagliardetto requested changes

2018-06-22 09:44 UTC, gagliardetto commented on stable/rocketchat/template.json
> +		"size": 10
The max volume size allowed is 8 (GB)

2018-06-24 01:30 UTC, Zahaby-magalix commented
I updated the file 
please check it now

2018-06-24 16:13 UTC, gagliardetto approved these changes

2018-06-24 16:13 UTC, merged